### ISSUE TITLE
Remove lib directory

### ISSUE THREAD

**Issue by aaronshaf** [uniflow/uniflow#2]
One will rarely want to require the root file anyway. Better to be able to:

``` javascript
import createStore from 'uniflow/createStore'
```

than

``` javascript
import createStore from 'uniflow/lib/createStore'
```

Also, in the future if we want a immutable-store.js / createImmutableStore, then we wouldn't want to force the inclusion of the immutable.js library in bundles.

**Comment by brentropy** [comment]
What about:

``` js
import {createStore} from 'uniflow'
```

I would rather the file structure be an implementation detail and not ever have it be relied on as "public API".
